name: Linting
on:
  push:
    branches-ignore:
      - main

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        reporter: github-pr-check
        files: docs/src
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
